Migrated to Python3 and added create_ticket() REST functionality
osuosl/formsender pull request #91
Opened 2023-01-11 23:38 UTC by antoniagaete

I only commented out things I changed when change to API based, especially encoding keys/values in `create_msg()`, just in case that's still necessary. It's my understand that python3 is already encoded though

A few questions I have: 
- should the variables when creating the tracker be hard coded like they are now? (line 527)
- when creating the ticket, I set the queue to 'OSLSupport'. I imagine since this is a form submission for a hosting request it will always be the same queue, but not sure if this is the correct one

2023-01-12 00:57 UTC, ramereth requested changes
I'd prefer if you just removed the commented code as it will be still in the git history and makes it harder to read the code diffs.

Also, we should add some simple CI to this PR via the Github Actions. Take a look at this [doc](https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python) to see how you do it. I'd prefer this file be `.github/workflows/ci.yml`

2023-01-12 00:57 UTC, ramereth commented on request_handler.py
> +    tracker = rt.rest2.Rt('http://support.osuosl.org/REST/2.0/', http_auth=requests.auth.HTTPBasicAuth('root', 'password'))
I'd have these in CONF settings:
1. URL (make it easier for testing), in production we should be using https FWIW
2. username
3. password

Now, I did enable Auth Tokens in RT (although there are extra steps to get this to work in test-kitchen. I'd prefer to go that route if possible. Let me know if you want help with that.

2023-01-12 00:57 UTC, ramereth commented on request_handler.py
> +    tracker.create_ticket('OSLSupport',
As you noted in your original description, we'll need to change this based on the form. Each form will likely have it's own queue that it will send to.

2023-01-12 00:57 UTC, ramereth commented on requirements.txt
>  Werkzeug==0.10.4
Shouldn't `rt` be included here? Are there any other deps that have changed? You should be running the following to update this:
```
pip freeze > requirements.txt
```

2023-01-20 19:27 UTC, antoniagaete commented
The changes I made that allow any queue to be used will require a change in the html files on the pelican site:
I changed the `send_to` value under the "formsender settings" section at the bottom of each html form to directly reflect the queues we already have on RT, since REST API is case sensitive

2023-01-20 22:52 UTC, ramereth requested changes

2023-01-20 22:52 UTC, ramereth commented on .github/workflows/ci.yml
> +    runs-on: ubuntu-latest
Let's run this on the following versions:
```suggestion
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
```

2023-01-20 22:52 UTC, ramereth commented on .github/workflows/ci.yml
> +          architecture: 'x86'
Let's use the matrix above with the following. Also remove the architecture as I don't think we need to set it.
```suggestion
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
```

2023-01-23 21:13 UTC, ramereth commented on .github/workflows/ci.yml
> +    runs-on: ubuntu-latest
@antoniagaete it looks like some of those versions can only be run on some ubuntu platforms unfortunately. You might need to split this job up or remove some of those versions to make this simpler.

2023-01-24 18:20 UTC, antoniagaete commented on .github/workflows/ci.yml
> +    runs-on: ubuntu-latest
I ended up removing them, but let me know if you want me to split up the job instead

2023-01-24 19:39 UTC, Codysseus commented on request_handler.py
> +        #if self.time_diff < 1 and self.rate > conf.get('CEILING')
Don't forget to remove commented code ;)

2023-01-24 19:39 UTC, Codysseus commented on tests.py
> +            #                                     msg_send.as_string())
Here as well! :)

2023-01-25 00:43 UTC, ramereth commented on tests.py
> +            #                                     msg_send.as_string())
@Codysseus :wave:

2023-01-27 18:10 UTC, ramereth commented on .github/workflows/ci.yml
> +    runs-on: ubuntu-latest
Let's just test for 3.6, 3.9 and 3.10

2023-02-02 17:18 UTC, ramereth requested changes
Please also do the following:
- Remove `.travis.yml`
- Update the documentation (`README` and anything under `docs`/)

2023-02-02 17:18 UTC, ramereth commented on Dockerfile
> +FROM python:3.10
I took a stab at this and I think the following for the `Dockerfile` will be good:

```dockerfile
FROM python:3.10-alpine
COPY requirements.txt /formsender/requirements.txt
WORKDIR /formsender
RUN pip install -r requirements.txt
COPY . /formsender
COPY conf.py.dist /formsender/conf.py
ENTRYPOINT ["python"]
CMD ["request_handler.py"]
EXPOSE 5000
```
However, ideally I'd like to be able to set the secrets via an environment variable in the Docker container doing something similar to [this](https://medium.com/@dreamferus/environment-variables-in-python-docker-49b7b88cc1e4).

I also think we should just remove the `docker-compose.yml` as it's not really needed I think.

2023-02-02 17:23 UTC, ramereth commented
@antoniagaete Forgot to mention that we should also clean up `conf.py.dist` by doing the following:
- Remove any unused options
- Remove the fake secrets for `TOKEN` and `RECAPTCHA_SECRET`  and comment those out

2023-02-06 20:56 UTC, ramereth commented on .github/workflows/ci.yml
> +    runs-on: ubuntu-latest
Add the following now that you're using environment variables:
```suggestion
    runs-on: ubuntu-latest
    env:
        TOKEN: test-token
        RECAPTA_SECRET: recapta-test
```
Or maybe there's a more elegant way to handle this if the environment variable isn't set... I'm not sure.

2023-02-06 22:41 UTC, ramereth commented on .github/workflows/ci.yml
> +      RECAPTCHA_SECRET: "6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe"
Please change these to something fake

2023-02-07 19:41 UTC, ramereth commented
@antoniagaete please fix the CI errors

2023-05-09 17:08 UTC, merged