Removing unneeded files and updating docs
osuosl/formsender pull request #96
Opened 2023-05-12 16:53 UTC by antoniagaete

2023-05-15 18:52 UTC, ramereth requested changes
- I'm pretty sure `__init__.py` is required or is it because it's at the root?
- Have you gone through each function to see if there is code we no longer need?

2023-05-15 18:52 UTC, ramereth commented on formsender/wsgi.py
> -    application = create_app()
I'd prefer to keep this, but update it. It seems as though the old [raven-python](https://github.com/getsentry/raven-python) client was deprecated and they now recommend to use [sentry-python](https://github.com/getsentry/sentry-python) instead.

Please do the following:
- Add sentry-python to `requirements.txt`
- Update this code to work properly. Only load sentry if we have the proper config set
- Update `entrypoint` to use `formsender.wsgi` instead of `request_handler:create_app()`
- Add/update environment variables in the cookbook so we can set the API token for Sentry.

2023-05-15 18:52 UTC, ramereth commented on request_handler.py
> -
- You should remove this also from `requirements.txt`
- Are there any other modules we're no longer using?

2023-05-26 20:19 UTC, ramereth requested changes

2023-05-26 20:19 UTC, ramereth commented on conf.py.dist
> +SENTRY_URI = os.environ['SENTRY_URI']
Something is up with how this line ends. Can you please fix it with your editor?

2023-05-26 20:19 UTC, ramereth commented on formsender/wsgi.py
> +        capture_exception(e)
I'm assuming this is for temporary testing? if so, please remove it.

2023-06-01 18:29 UTC, ramereth reviewed
Outside of my minor nitpick, does this PR require any changes in the cookbook? I _think_ we can merge this/deploy this as-is and then we can update the cookbook later to properly setup Sentry.

2023-06-01 18:54 UTC, antoniagaete commented
> Outside of my minor nitpick, does this PR require any changes in the cookbook? I _think_ we can merge this/deploy this as-is and then we can update the cookbook later to properly setup Sentry.

With these changes, I don't think we will need to update any cookbooks since the Sentry uri isn't required. When we add Sentry to the container, we'll have to update the recipe to include the Sentry env variable in the docker container, which we need to add to the encrypted databag.

2023-06-01 22:09 UTC, ramereth approved these changes

2023-06-01 22:09 UTC, merged